### ISSUE TITLE
Unable to delete first letter in notes box after you start typing

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#778] opened 2022-04-14 15:13 UTC
**Summary:**

1. **What is actually happening:**

2. **What should be happening:**

3. **Steps to recreate:**

4. **Screenshots/GIF/Video recording**
Screenshots/video recordings of the issue are very helpful as well. Checking the browser's console for errors also provides developers with helpful debugging information. See [this guide](https://balsamiq.com/support/faqs/browserconsole/) for details on opening the develop console.

**Comment by levity** [comment] 2022-04-14 17:18
Duplicate of #753 -- i'm going to look into this now

**Closed by levity** 2022-04-14 17:18 UTC
Labels: bug, good first issue, 1
