### ISSUE TITLE
Click on selected circle name should take you to Epoch page.

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#1125] opened 2022-07-11 21:15 UTC
**What's happening:**
In the left nav menu, When user clicks on the currently selected circle, nothing happens (except the nav closes). 

<img width="188" alt="Screen Shot 2022-07-11 at 12 35 49 PM" src="https://user-images.githubusercontent.com/5608004/178573674-a19a3117-3a7a-48b7-b0c6-0d544262e48e.png">

**What should be happening:**
When the currently selected circle is clicked, the circle's epoch overview page should be navigated to.
HERE:
<img width="1278" alt="Screen Shot 2022-07-12 at 12 03 09 PM" src="https://user-images.githubusercontent.com/5608004/178573873-02505304-f042-4b3f-9e88-1bbc362b0298.png">

**Comment by levity** [comment] 2022-07-12 07:26
Duplicate of #1109?

I think there was a misunderstanding on the part of QA people because the
currently selected circle shows up twice in the menu, and only one of them
links to the history page.

**Comment by spydermonkee** [comment] 2022-07-12 19:05
This is not a duplicate, but rather seems that it was not implemented this way from the start.

**Comment by spydermonkee** [comment] 2022-07-13 00:22
@levity - Actually, now that I look more closely at the title of #1109, it is a duplicate, but @crabsinger closed that issue, though this is still not working correctly for me. We can just leave this issue open now to represent this need. I think that it's important to resolve this before or very soon after merging #1114, since epoch mgmt will become a little harder to find after that if it's not easy to get to the epoch history page.

**Comment by levity** [comment] 2022-07-13 08:22
Was my guess right about the misunderstanding? Are you trying to click on
the first time the circle name shows in the menu, at the very top, not
where it’s listed among the others below?

**Closed** 2022-07-13 12:56 UTC
Labels: bug, good first issue, 1, Community
