### ISSUE TITLE
Live Epoch Give Amounts Displaying prior Epoch Give Amounts

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#333] opened 2021-12-02 13:16 UTC
During a live Epoch the Give amount on the map is displaying the prior epochs Give. (See Screenshot) 
![image](https://user-images.githubusercontent.com/82838264/144429155-86eb08d1-96f4-4c72-93e2-4cbd7b022d6e.png)

Reported by Tjark in Layer3 quest seekers circle as well

Please update the give amount to display the give from the currently selected Epoch at all times.

**Comment by exrhizo** [comment] 2021-12-02 23:55
I don't know how to reproduce this, I asked Reese...

**Comment by exrhizo** [comment] 2021-12-03 04:12
Figured it out.
Talking to Reese, it could be good to sync this with the map epoch, that can be it's own ticket.

**Comment by reeserj** [comment] 2021-12-13 14:33
@exrhizo can we close this one?

**Comment by spydermonkee** [comment] 2022-01-03 17:24
hi @exrhizo ! :-)   - This looks like it's been merged. Can this issue be closed?

**Closed** 2022-04-26 12:32 UTC
Labels: bug
