### ISSUE TITLE
Circles Page displays expired nominees in total Nominees number

### ISSUE THREAD

**Issue by sshmm** [coordinape/coordinape#790] opened 2022-04-16 23:36 UTC
Circles Page shows expired nominees in total Nominees number

1. **What is actually happening:**
The number of Nominees in circles switching page is showing total number of nominees including expired nominees

3. **What should be happening:**
Only Active nominees should be displayed

4. **Steps to recreate:**
1- Add a nominee
2- Wait until the nomination period expires without successful nomination or modify the expiry date on hasura console
3- Switch to the circles page and check the Nominees number

5. **Screenshots/GIF/Video recording**
![image](https://user-images.githubusercontent.com/34943689/163694281-a8f82d70-c658-4c78-931b-0d947bd2497d.png)

**Comment by levity** [comment] 2022-04-17 00:10
Duplicate of #781

**Closed** 2022-04-17 00:10 UTC
Labels: bug
