### ISSUE TITLE
Write Shared Code: Unified Environment for Tests

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#489] opened 2022-01-27 15:15 UTC
### Specification

At the moment, there are two separate test suites in the front-end app: one for hardhat, which tests contracts, and one for the React app, which tests components and other UI code. We need to set up a test environment that will allow a single test to do both.

The hardhat test suite is already starting a hardhat node for its own tests; we probably just need to figure out what to call to perform that same setup/teardown in the Jest test environment.

**Comment by levity** [comment] 2022-03-08 19:37
Duplicate of #527

**Closed** 2022-03-08 19:37 UTC
Labels: Phase 2, Golden Path, Finish UI Functionality
