### ISSUE TITLE
ReceiveInfo popup zIndex isn't high enough wrt givebeta page

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#1682] opened 2022-11-18 08:47 UTC
**Summary:**

The ReceiveInfo panel is underneath the allocate rows
![image](https://user-images.githubusercontent.com/95149165/202660106-89430469-b289-4785-8dd4-69351d93b1f2.png)

**Comment by yahiamarzouk** [comment] 2022-11-18 10:22
i have been able to recreate the problem 
i went to code and added the zindex
i fixed the problem
removed my zindex to make a new branch...then paste it there
the problem is fixed by it's own, and can't recreate it  :')

**Closed** 2022-11-18 16:43 UTC
Labels: bug, good first issue, Community
